package de.tobias.investmentradar

internal fun testInvestmentItem(
    id: String = "x",
    type: String = "AKTIE",
    status: String = "BEOBACHTEN",
    recommendation: String = "WATCH",
    scoreTotal: Int? = 70,
    coverage: Int? = 100,
    risk: Int = 2,
    priceEur: Double? = null,
    portfolioOnly: Boolean = false
): InvestmentItem = InvestmentItem(
    id = id,
    type = type,
    name = id,
    ticker = id.uppercase(),
    isin = "",
    tradeRepublicName = id,
    status = status,
    allocation = 0,
    risk = risk,
    price = null,
    priceEur = priceEur,
    currency = "EUR",
    fxRateToEur = 1.0,
    fxSource = "",
    fxDelayed = false,
    fxAsOf = null,
    percentChange = null,
    marketOpen = null,
    dataSource = "",
    dataDelayed = false,
    dataError = null,
    scoreTotal = scoreTotal,
    scoreQuality = null,
    scoreValuation = null,
    scoreGrowth = null,
    scoreMomentum = null,
    scoreRisk = null,
    coverage = coverage,
    recommendation = recommendation,
    recommendationReasons = emptyList(),
    momentum = null,
    fundamentals = null,
    analysisAsOf = null,
    portfolioOnly = portfolioOnly
)