#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MARKET="$ROOT/backend/src/lib/market.mjs"
SUPPORT="$ROOT/backend/src/lib/marketSupport.mjs"
DASH="$ROOT/backend/src/lib/dashboard.mjs"
FXCACHE="$ROOT/backend/src/lib/fxCache.mjs"
MODELS="$ROOT/android/app/src/main/java/de/tobias/investmentradar/Models.kt"
API="$ROOT/android/app/src/main/java/de/tobias/investmentradar/ApiClient.kt"
MAIN="$ROOT/android/app/src/main/java/de/tobias/investmentradar/MainActivity.kt"
GRADLE="$ROOT/android/app/build.gradle.kts"

grep -q 'eurofxref-daily.xml' "$MARKET"
grep -q 'normalizeEcbDailyXml' "$SUPPORT"
grep -q 'loadEurRateDetails' "$DASH"
grep -q 'mergeFxRatesWithCache' "$DASH"
test -f "$FXCACHE"
grep -q 'val fxSource: String' "$MODELS"
grep -q 'val fxDelayed: Boolean' "$MODELS"
grep -q 'val fxAsOf: String?' "$MODELS"
grep -q 'fxSource = o.optString("fxSource"' "$API"
grep -q 'Text("FX ${item.fxSource}' "$MAIN"
grep -q 'versionCode = 19' "$GRADLE"
grep -q 'versionName = "1.1.18"' "$GRADLE"
