#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MAIN="$ROOT/android/app/src/main/java/de/tobias/investmentradar/MainActivity.kt"
VM="$ROOT/android/app/src/main/java/de/tobias/investmentradar/MainViewModel.kt"
STORE="$ROOT/android/app/src/main/java/de/tobias/investmentradar/PortfolioStore.kt"
GRADLE="$ROOT/android/app/build.gradle.kts"

grep -q 'val positions by vm.positions.collectAsState()' "$MAIN"
grep -q 'PurchaseHistoryDialog' "$MAIN"
grep -q 'Kaufhistorie' "$MAIN"
grep -q 'Investierter Betrag in €' "$MAIN"
grep -q 'Stückzahl / Anteile' "$MAIN"
grep -q 'Transaktionen verwalten' "$MAIN"
grep -q 'Unrealisierter G/V' "$MAIN"
grep -q 'vm.upsertPurchase' "$MAIN"
grep -q 'vm.removePurchase' "$MAIN"
grep -q 'val positions: StateFlow<Map<String, PortfolioPosition>>' "$VM"
grep -q 'fun upsertPurchase(itemId: String, purchase: PortfolioPurchase)' "$VM"
grep -q 'fun removePurchase(itemId: String, purchaseId: String)' "$VM"
grep -q 'fun readPositions(context: Context): Map<String, PortfolioPosition>' "$STORE"
grep -q 'private const val LEGACY_KEY = "holding_ids"' "$STORE"
grep -q 'putStringSet(LEGACY_KEY, ids)' "$STORE"
grep -q 'purchasesKey' "$STORE"
grep -q 'versionCode = 23' "$GRADLE"
grep -q 'versionName = "1.1.22"' "$GRADLE"
