#!/usr/bin/env bash
set -euo pipefail
UI="android/app/src/main/java/de/tobias/investmentradar/AlertsScreen.kt"
STATE="android/app/src/main/java/de/tobias/investmentradar/AlertCenterState.kt"

grep -q 'ALL("Alle")' "$STATE"
grep -q 'BUY("Kauf")' "$STATE"
grep -q 'REVIEW("Prüfen")' "$STATE"
grep -q 'SELL("Verkauf")' "$STATE"
grep -q 'level.equals("THRESHOLD"' "$STATE"
grep -q 'filter.matches(stored.alert.level)' "$UI"
grep -q 'Alle gelesen' "$UI"
grep -q 'Alarmeinstellungen' "$UI"
grep -q 'onDelete' "$UI"
grep -q 'onClear' "$UI"

grep -q 'private fun alertBadgeLabel' "$UI"
grep -q '"PROGNOSE"' "$UI"
grep -q 'private fun alertAccentColor' "$UI"
grep -q 'private fun formatAlertTimestamp' "$UI"
grep -q 'HorizontalDivider' "$UI"
grep -q 'Text("Warum der Radar reagiert"' "$UI"
grep -q 'Text("NEU"' "$UI"
grep -q 'contentDescription = "Alarm löschen"' "$UI"

# Prognose-Alarme werden vollständig auf Deutsch strukturiert dargestellt.
grep -q 'private fun ForecastAlertSummary' "$UI"
grep -q '"PROGNOSE · 12 MONATE"' "$UI"
grep -q 'Text("Vorher:' "$UI"
grep -q '"Pessimistisch"' "$UI"
grep -q '"Erwartet"' "$UI"
grep -q '"Optimistisch"' "$UI"
grep -q '"AUFWÄRTS"' "$UI"
grep -q '"ABWÄRTS"' "$UI"
grep -q '"SEITWÄRTS"' "$UI"
